module.exports = {
	excludeFiles: [
		'node_modules/**'
	],
	disallowAttributeConcatenation: null,
	disallowAttributeInterpolation: null,
	disallowBlockExpansion: true,
	disallowClassAttributeWithStaticValue: null,
	disallowClassLiteralsBeforeAttributes: null,
	disallowClassLiteralsBeforeIdLiterals: true,
	disallowClassLiterals: null,
	disallowDuplicateAttributes: true,
	disallowHtmlText: null,
	disallowIdAttributeWithStaticValue: null,
	disallowIdLiteralsBeforeAttributes: null,
	disallowIdLiterals: null,
	disallowMultipleLineBreaks: null,
	disallowSpaceAfterCodeOperator: null,
	disallowSpacesInsideAttributeBrackets: true,
	disallowSpecificAttributes: null,
	disallowSpecificTags: null,
	disallowStringConcatenation: true,
	disallowStringInterpolation: null,
	disallowTagInterpolation: null,
	maximumNumberOfLines: null,
	requireClassLiteralsBeforeAttributes: true,
	requireClassLiteralsBeforeIdLiterals: null,
	requireIdLiteralsBeforeAttributes: true,
	requireLineFeedAtFileEnd: true,
	requireLowerCaseAttributes: true,
	requireLowerCaseTags: true,
	requireSpaceAfterCodeOperator: true,
	requireSpacesInsideAttributeBrackets: null,
	requireSpecificAttributes: [
		{img: 'alt'},
		{input: 'type'},
		{'input[type=submit]': 'value'}
	],
	requireStrictEqualityOperators: true,
	validateAttributeQuoteMarks: '"',
	validateAttributeSeparator: null,
	validateDivTags: true,
	validateIndentation: '\t',
	validateLineBreaks: null,
	validateSelfClosingTags: true
};
